/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyMap {
    'reader': string;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface MyMap extends JSXBase.HTMLAttributes {
    'reader'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'my-map': MyMap;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLMyMapElement extends Components.MyMap, HTMLStencilElement {}
  var HTMLMyMapElement: {
    prototype: HTMLMyMapElement;
    new (): HTMLMyMapElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'my-map': HTMLMyMapElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

